spring:
  application:
    name: journal-service

  threads:
    virtual:
      enabled: true

  cloud:
    aws:
      s3:
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION:us-east-1}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}

  task:
    scheduling:
      pool:
        size: 2

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: journal-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      timeout: 60000

resilience4j:
  ratelimiter:
    instances:
      journalApi:
        limitForPeriod: 100
        limitRefreshPeriod: 1m
        timeoutDuration: 60s

journal:
  api:
    base-url: "https://msapi.top-academy.ru/api/v2"
    application-key: 6a56a5df2667e65aab73ce76d1dd737f7d1faef9c52e8b8c55ac75f565d8e8a6
    user-agent: "itt-journal-service/1.0"
    journal-url: "https://journal.top-academy.ru"
    timeout:
      connect: 10000
      read: 15000

  token:
    refresh-interval: 14400000
    refresh-before-expiry: 300
    max-retry-attempts: 3

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

kafka:
  homework-execution-topic: homework-execution
  homework-execution-result: homework-result

outbox:
  batch-size: 100
  max-attempts: 5
  retry-delay-seconds: 60
  relay-interval-ms: 5000

auto-homework:
  check-interval-ms: 21600000  # 6 часов

s3:
  bucket: homeworks-solutions

crypto:
  secret-key: ${ENCRYPTION_KEY}

logging:
  level:
    com.aquadev.ittopai: DEBUG
    org.springframework.web: INFO
    org.springframework.web.client: DEBUG

server:
  port: ${SERVER_PORT:8080}
