journal:
  api:
    base-url: "http://localhost:8090/api/v2"

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.aquadev.journalservice.config.journal.LoggingClientHttpRequestInterceptor: DEBUG