logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.aquadev.journalservice.config.journal.LoggingClientHttpRequestInterceptor: DEBUG