name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew --no-daemon clean assemble
        env:
          SPRING_PROFILES_ACTIVE: aot

      - name: Run tests
        run: ./gradlew --no-daemon test
        env:
          SPRING_PROFILES_ACTIVE: aot

  docker:
    name: Build Docker image
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: ./Dockerfile
          tags: it-top-ai:ci
          push: false
          load: false
          build-args: |
            CI=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
